data1=read.csv(file = "C:\\Users\\Jannat\\Desktop\\Datasets for Rscript\\FGFR3.csv",header = TRUE)
data2=read.csv(file = "C:\\Users\\Jannat\\Desktop\\Datasets for Rscript\\HRAS.csv",header = TRUE)
data3=read.csv(file = "C:\\Users\\Jannat\\Desktop\\Datasets for Rscript\\RB1.csv",header = TRUE)
data4=read.csv(file = "C:\\Users\\Jannat\\Desktop\\Datasets for Rscript\\TP53.csv",header = TRUE)
data5=read.csv(file = "C:\\Users\\Jannat\\Desktop\\Datasets for Rscript\\TSC1.csv",header = TRUE)
plot(data1$FGFR3,type="o",col="blue",axes=FALSE)
axis(1,at=1:53,lab=data1$Samples,las=2)
axis(2,las=1)
lines(data1$hsa.let.7i, type="o", pch=22,lty=2,col="red")
axis(4,las=1)
title(main="FGGR3 vs hsa-let-7i correlation for 53 Tumor samples",col.main="blue",font.main=4)
plot(data1$FGFR3,type="o",col="blue",axes=FALSE)
axis(1,at=1:53,lab=data1$Samples,las=2)
axis(2,las=1)
lines(data1$hsa.miR.212, type="o", pch=22,lty=2,col="red")
axis(4,las=1)
title(main="FGGR3 vs hsa-miR-212 correlation for 53 Tumor samples",col.main="blue",font.main=4)
